### ISSUE TITLE
心跳

### ISSUE THREAD

**Issue by flwmxd** [sunflyer/SimpleNetkeeper#2]
java版本的支持心跳吗？

**Comment by sunflyer** [comment]
java版本并没有心跳。

**Comment by krrr** [comment]
@sunflyer 我才发现你的首页上也有个不是java写的2.5版，那个支持心跳吗？
浙江金华电信今天早上开始心跳了，20分钟断线一次

edit--------
看来那个也没有心跳模拟。但我在不断重拨一段时间后突然一直691了，还以为账号被封了。又过了一会儿能登陆了，心跳也没了……
