### ISSUE TITLE
请问怎样才能同时上内外网？

### ISSUE THREAD

**Issue by marswong** [sunflyer/SimpleNetkeeper#3]
如题，有没有办法同时上内网和外网呢？折腾了很久了。

**Comment by sunflyer** [comment]
一般的路由器是做不到的

**Comment by shincurry** [comment]
开两个路由器吧

**Comment by marswong** [comment]
想了很久,要同时上内外网的话始终要走学校的网关...

还有一个问题就是APP那个切换内网功能无法使用,我目前用的是水星**MW305R**(13年的款啊?),固件如下:

```
当前硬件版本：MW305R 10.0 00000000
当前软件版本：2.3.28 Build 160509 Rel.51342n
```

(ps:论坛我注册了不能发帖,只能来这里提了,谢谢)

**Comment by sunflyer** [comment]
160509是新版本固件了，切换内网只有旧版本可用

**Comment by marswong** [comment]
好吧,谢了
