### ISSUE TITLE
代码的完整度

### ISSUE THREAD

**Issue by krrr** [sunflyer/SimpleNetkeeper#4]
代码各处都有空缺，这是故意的吗？比如“现在连接”按钮的动作方法是空的，ras拨号用的JNI类的类名方法名都是错的

不过改正之后真的可以用，我是浙江金华的，感谢作者……
如果不是故意要留空的话我可以开个pr

**Comment by sunflyer** [comment]
RAS那个是因为更新以后没有Implementation，1.2是改过界面的，接口也调整了，所以JNI一直没去实现它

**Comment by krrr** [comment]
意思是java这边的类名要改成和cpp那边的一样吗

**Comment by sunflyer** [comment]
我没记错的话这个cpp我是直接用java的那个工具生成的。。。从这个类

**Comment by shincurry** [comment]
请问你们需要 iOS 版嘛（滑稽

**Comment by krrr** [comment]
啊，你说的是`cn_sunflyer_simpnk_control_DialWindows.h`吗，只改头文件不改cpp不行的吧？我的意思是要不要保持现在的c++代码不动只改java，因为cpp代码和你附带的dll里的导出函数都是旧的，包名是cqxinli

**Comment by sunflyer** [comment]
那样的话只改java也行。。。

**Comment by krrr** [comment]
@ShinCurry 闪讯的无线版还有人用？我这边信号差到连不上，也没人修，基本等于不存在
